#!/bin/bash
# -*- coding: utf-8 -*-

# Checker
#
# Provides automated testing using shellcheck and shfmt
#
# Input:  Supply one filename [defaults to ./spkg]
# Output: Writes information to:
#         - stderr
#         - ./shellcheck.log
#         - ./shfmt.log

echo_information() {
  printf '\x1b[32mInformation:\x1b[0m %s\n' "$*" >&2
}

echo_warning() {
  printf '\x1b[31mWarning!\x1b[0m %s\n' "$*" >&2
}

echo_error() {
  printf '\x1b[31mError!\x1b[0m %s\n' "$*" >&2
}

declare -r Executable="${1:-./spkg}"

if [[ ! -f "${Executable}" ]]; then
  echo_error "Executable not found!"
else
  echo_information "Checking ${Executable}"
fi

Warnings=0
Issues=0

if ! command -v shellcheck &>/dev/null; then
  echo_warning 'Shellcheck not installed'
  ((Warnings++))
else
  if ! shellcheck "${Executable}" &>shellcheck.log; then
    echo_error "Failed shellcheck linting"
    ((Issues++))
  else
    echo_information "Passed shellcheck linting"
  fi
fi

if ! command -v shfmt &>/dev/null; then
  echo_warning 'shfmt not installed'
  ((Warnings++))
else
  if ! shfmt -d -ci -i 2 "${Executable}" &>shfmt.log; then
    echo_error "Failed shfmt linting"
    ((Issues++))
  else
    echo_information "Passed shfmt linting"
  fi
fi

if ((Warnings > 0)); then
  exit 1
fi

if ((Issues > 0)); then
  exit 1
fi

exit 0
